#!/bin/bash

echo "🧪 Probando el sistema de reintentos de Gemini..."
echo ""
echo "📋 Para probar manualmente:"
echo "1. Abre la aplicación en http://localhost:5173"
echo "2. Ve a la pestaña 'Importar desde PDF'"
echo "3. Configura tu API key de Gemini"
echo "4. Sube un PDF cuando el servicio esté experimentando errores 503"
echo ""
echo "✅ Comportamiento esperado:"
echo "- Verás logs en la consola indicando reintentos automáticos"
echo "- El sistema probará múltiples modelos: 2.5-pro → 2.5-flash → 2.5-flash-lite → 2.0-flash-15 → 2.0-flash-lite"
echo "- Cada modelo se intentará hasta 3 veces con delays exponenciales"
echo "- El usuario verá mensajes informativos sobre el progreso"
echo ""
echo "📊 Logs de ejemplo esperados:"
echo "🔄 Modelo gemini-2.5-pro - Intento 1/3"
echo "❌ Error con modelo gemini-2.5-pro, intento 1: 503 Service Unavailable"
echo "⏳ Modelo sobrecargado, reintentando en 4000ms..."
echo "🔄 Modelo gemini-2.5-pro - Intento 2/3"
echo "❌ Error con modelo gemini-2.5-pro, intento 2: 503 Service Unavailable"
echo "⏳ Modelo sobrecargado, reintentando en 8000ms..."
echo "🔄 Probando con modelo: gemini-2.5-flash"
echo "✅ Exitoso con modelo gemini-2.5-flash en intento 1"
echo ""
echo "🎯 El proceso debería completarse exitosamente con un modelo alternativo."